ktor:
  application:
    modules:
      - re.chasam.ApplicationKt.module
  deployment:
    port: 8080
database:
  scheme: mongodb
  host: '127.0.0.1'
  port: 27017
  name: tournament
  collection: users